### PR TITLE
Data Farming page - Display per-asset APY

### LINKED ISSUE #394: Display assets APY inside data explorer table

### PR DESCRIPTION
**Pull request by KatunaNorbert**
Fixes #394.

### CODE REVIEW

**Comment by idiom-bytes** [comment]
Waiting for review/feedback of APY/APR

**Review by idiom-bytes — DISMISSED** [review]
[display asset-apys]
hi @KatunaNorbert, i think the latest changes to issue394-display-asset-APYs would force me to have to build docker
i.e. we need to maintain support fo `npm run dev`

when i build w/ npm run dev i get the follow (screenshot attached)
further, the configuration would not work in staging/production because `--port 4005 --host 0.0.0.0` was deleted

everything else looked good. I'm pushing some adjustments to the tooltip

Screenshot from 2022-11-22 16-52-31

**Comment by idiom-bytes** [comment]
I have proposed the following changes to be merged to this PR.
https://github.com/oceanprotocol/df-web/pull/403

Specifically, renaming "APY" to "RoundAPY" and improving the descriptions.

Users should understand that this number can change significantly between when the round:
- starts (x1)
- ends (y1)
- restarts (x2)

**Comment by KatunaNorbert** [comment]
I was removing things in order to debug the build error which prevented the Vercel Preview to kick off.
I added back all the removed configs so It should work fine on Docker.

**Pull request merged**
