### PR TITLE
Added lastRoundVolume

### LINKED ISSUE #533: Make sure roundVolume and lastRoundVolume are available
- [x] Double checked RoundVolume was still there
- [x] Added lastRoundVolume

### PR DESCRIPTION
**Pull request by idiom-bytes**
Fixes #533 
- Verified roundVolume was still available
- Added lastRoundVolume as another data point

### CODE REVIEW

**Review by EnzoVezzaro — DISMISSED** [review]
LGTM 👍🏽

**Review by KatunaNorbert — DISMISSED** [review]

**Comment by KatunaNorbert** [comment]
Right, it's the same for me, you need to refresh otherwise it's undefined. Let me look into this.

**Comment by EnzoVezzaro** [comment]
> Are you sure this is correct? Says `undefined` for every asset... If they didn't have any volume last round it should be 0 rather than `undefined`:
> 
> image

yeah, I'm having the same issue. Also when you remove and add a column the tooltip on that column disappears (this doesn't seems related to this PR, but maybe it can be worked out in here).

**Review by EnzoVezzaro — APPROVED** [review]
great job @KatunaNorbert 👏🏽 not issues found

**Review by jamiehewitt15 — APPROVED** [review]
Yeah looks good now

**Comment by idiom-bytes** [comment]
```Are you sure this is correct? Says undefined for every asset... If they didn't have any volume last round it should be 0 rather than undefined:```

I worked on it after seeing the issue so by the time I ran again, it all seemed to work. I thought it had to do with fresh assets without a lastRound.value, so I bound it to a min value of zero, and it all seemed to work.

Checking with Norbert..

**Comment by idiom-bytes** [comment]
I think I can just check for typeof !== undefined.
Will validate asap.

**Comment by KatunaNorbert** [comment]
@idiom-bytes Yes, I fixed the issues. I'm merging this one.

**Pull request merged**
