### PR TITLE
Fix claim rewards for Safari mobile and Metamask

### LINKED ISSUE #141: User is unable to claim rewards in Metamask from other browsers
Bug:
User has earned rewards, clicks the claim button, but receives an error.
"Failed to claim Data Farming rewards!"
https://t.me/Farm_Ocean/174556

Wallet: Metamask
Browser(device): safari (iOS)

### PR DESCRIPTION
**Pull request by KatunaNorbert**
Fixes #141

### CODE REVIEW

**Comment by idiom-bytes** [comment]
I have not yet tested this but the code LGTM

**Comment by KatunaNorbert** [comment]
I still haven't manage to fix the bug on the specified configuration, let's keep it open

**Comment by jamiehewitt15** [comment]
Has this been abandoned? No activity here since august and the last commit was 8th July 2022

**Comment by KatunaNorbert** [comment]
I think we can close it, I remember being able to reproduce it with some specific mobile browser + wallet configuration, but can't find where I mentioned those, probably the issue was closed.
It was an edgecase so wasn't other complains since since then, we can reopen it If someone runs into it again.

**Pull request closed without merging**
