### PR TITLE
restore farm table title style

### PR DESCRIPTION
**Pull request by EnzoVezzaro**
Fixes # .

Changes proposed in this PR:

- restore farm title style after last deployment

### CODE REVIEW

**Comment by KatunaNorbert** [comment]
@EnzoVezzaro What issue does this actually solve, I can't see it, can you leave a screenshoot?

**Comment by EnzoVezzaro** [comment]
> @EnzoVezzaro What issue does this actually solve, I can't see it, can you leave a screenshoot?

yeah sure, it's the title column in farm table.

Screenshot 2023-04-14 at 09 30 51

**Comment by KatunaNorbert** [comment]
I see, but looks like there is another issue now. The title is to short:

Screenshot 2023-04-14 at 16 40 58

**Comment by EnzoVezzaro** [comment]
> I see, but looks like there is another issue now. The title is to short:
> 
> Screenshot 2023-04-14 at 16 40 58

mmmm....  that looks like another isssue. I just added 2 lines of code: one for the font-weight and the other for margin-bottom. It shouldn't impact any truncate, but i'll check.

**Comment by EnzoVezzaro** [comment]
I can see it fine. maybe the viewport?

Screenshot 2023-04-14 at 09 52 11

**Comment by KatunaNorbert** [comment]
@EnzoVezzaro Issue seems to be browser related. I get the issue I mention on Safari.

**Review by jamiehewitt15 — APPROVED** [review]
This fix looks good to me

**Review by jamiehewitt15 — APPROVED** [review]

**Pull request merged**
